microsoft/content-processing-solution-accelerator

.github/workflows/build-docker-image.yml
**Configurations Settings**
**Trigger Conditions:**
Runs on pushes and pull requests (for branches: main, dev, demo, hotfix) as well as manually via workflow_dispatch.
**Environment Setup:**
Uses Ubuntu runners and sets environment variables for Azure Container Registry (ACR) credentials from secrets.
**Sets up Docker Buildx**
**Conditional ACR Login:**
The login step executes only if the branch name is one of main, dev, demo, or hotfix, ensuring that pull requests or non-designated branches do not trigger a login.
**Dynamic Tagging with Date:**
Determines the Docker image tag based on the branch name:
main → latest
dev → dev
demo → demo
hotfix → hotfix
All other branches default to pullrequest-ignore
**Additionally, the workflow retrieves the current date (formatted as YYYY-MM-DD) and …
=> feat: CI/CD Workflow for Building and Pushing Docker Images

.github/workflows/build-docker-image.yml
This workflow triggers on pushes, pull requests, and manual dispatch for the main, dev, demo, and hotfix branches. It logs into Azure Container Registry conditionally, captures the current date, and sets two tags for each Docker image—one based on the branch (e.g., dev) and another appending the date (e.g., dev-2025-04-03). The images are built from the root directory of each project and pushed only for recognized branches.
* ...
=> feat: Build & Push Docker Images with Dual Tagging

.github/workflows/create-release.yml
This PR introduces a GitHub Actions workflow (create-release.yml) that automates semantic versioning and release note generation based on conventional commit messages. It uses the semantic-release toolset to:
- Analyze commit messages
- Generate changelogs
- Create GitHub releases
This helps ensure consistent release practices across the project and eliminates manual version bumps 
- The workflow is triggered only on push to the main branch.
- Proper permissions (contents and pull-requests) are granted.
- Uses the correct semantic-release plugins and presets.
- The GITHUB_TOKEN is correctly referenced from secrets.
- Workflow syntax and indentation are correct and valid.
- Confirm version tagging format as v${version}.
- Outputs of the release step are …
=> feat: Add Create-Release Workflow Using Semantic Release

docs/quota_check.md, infra/scripts/quota_check_params.sh
* ...
This pull request introduces significant enhancements to the `infra/scripts/quota_check_params.sh` script, focusing on adding verbosity control, improving parameter handling, and refining logging mechanisms.
Key changes include:
* Introduced a `--verbose` flag to enable detailed logging. Added a `log_verbose` function to conditionally output logs based on the verbosity flag. [[1]](diffhunk://#diff-686f17dd7cf7e8af9b5575a7098de6011c9bc4b0cdc7aa3c631b66b0d5fe6975R2-L5) [[2]](diffhunk://#diff-686f17dd7cf7e8af9b5575a7098de6011c9bc4b0cdc7aa3c631b66b0d5fe6975R89)
* Implemented command-line argument parsing for `--models`, `--regions`, and `--verbose` options, with fallback to defaults if not provided. [[1]](diffhunk://#diff-686f17dd7cf7e8af9b5575a7098de6011c9bc4b0cdc7aa3c631b66b0d5fe6975R2 …
=> feat: add --models, --regions, and --verbose support

README.md, infra/scripts/quota_check_params.sh
* ...
This pull request includes changes to improve the readability and accuracy of the documentation and scripts. The most important changes include updating a file path in the `README.md` and improving the readability of a conditional statement in a shell script.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L66-R66): Corrected the file path for the quota check instructions guide from `./docs/Quota_Check.md` to `./docs/quota_check.md`.
Script improvements:
* [`infra/scripts/quota_check_params.sh`](diffhunk://#diff-686f17dd7cf7e8af9b5575a7098de6011c9bc4b0cdc7aa3c631b66b0d5fe6975L224-R225): Improved the readability of a complex conditional statement by adding line breaks and reformatting the logic.
No
Verify that …
=> fix: update link filename and remove text embedding check

docs/DeploymentGuide.md
=> docs: Updated documentation to use the correct file name for quota script

docs/DeploymentGuide.md
* Updated deployment guide documentation to include instructions on how to obtain the Tenant ID required for local deployment.
- [X ] No
* ...
=> docs: Add instructions to obtain tenant-id in deployment guide

.github/workflows/deploy.yml
- Replaced the logic for generating a unique solution prefix with a more consistent environment name using a timestamp and random suffix.
- Added createdDate tag while creating the resource group for better traceability and auditing.
- Added if: always() to ensure cleanup steps are executed regardless of prior job success/failure.
- Helps avoid leftover Azure resources and unnecessary costs due to partial failures.
Verify that the following are valid:
- Ensure the new environment name logic produces a valid and unique string.
- Verify the createdDate tag is correctly added in the resource group creation step.
- Confirm the cleanup step works as expected even if earlier steps fail, due to if: always().
=> fix: Update deploy.yml - Replace solution prefix logic, add createdDate tag and enforce cleanup with always()

README.md, docs/AzureAccountSetup.md, docs/DeploymentGuide.md
=> docs: updating deployment docs

docs/DeploymentGuide.md
Updating the model deployment capacity default value
* ...
* ...
=> docs: Update DeploymentGuide.md

infra/deploy_ai_foundry.bicep, infra/main.json
This pull request includes a minor change to the `infra/deploy_ai_foundry.bicep` file. The change comments out the `statisticsEnabled: false` property in two Cognitive Services account resources.
Details of the changes:
* [`infra/deploy_ai_foundry.bicep`](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L73-R73): Commented out the `statisticsEnabled: false` property in the `aiServices` resource definition.
* [`infra/deploy_ai_foundry.bicep`](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L93-R93): Commented out the `statisticsEnabled: false` property in the `aiServices_CU` resource definition.
* ...
* ...
=> fix: Update deploy_ai_foundry.bicep

src/ContentProcessor/pyproject.toml, src/ContentProcessor/requirements.txt, src/ContentProcessor/src/libs/application/application_context.py, src/ContentProcessor/src/libs/azure_helper/azure_openai.py, src/ContentProcessor/src/libs/base/application_main.py, src/ContentProcessor/src/libs/pipeline/handlers/evaluate_handler.py, src/ContentProcessor/src/libs/pipeline/handlers/map_handler.py, src/ContentProcessor/src/libs/semantic_kernel_extended/custom_execution_settings.py, src/ContentProcessor/uv.lock, src/ContentProcessorWeb/yarn.lock
replace openai sdk to semantic kernel support.
* ...
End to End content processing worked
* ...
=> refactor: replace open ai sdk to semantic kernel

.github/workflows/build-docker-image.yml
* ...
This pull request updates the `.github/workflows/build-docker-image.yml` file to improve how Docker image tags are generated and to standardize the use of the external registry. The changes ensure better flexibility and consistency in handling the registry URL by introducing a new step to retrieve the registry dynamically.
* Added a new step to dynamically retrieve the external registry URL and store it in the `GITHUB_OUTPUT` context for subsequent steps. (`[.github/workflows/build-docker-image.ymlL34-R42](diffhunk://#diff-5b40193e09025fd041de92d38c976d0b469e3ee85bef45a71d05d8b5078b1ee8L34-R42)`)
* Updated Docker image tags to use the dynamically retrieved registry URL (`steps.registry.outputs.ext_registry`) instead of the static `env.ACR_LOGIN_SERVER` variable for the …
=> fix: pipeline login server tag not found

docs/CustomizingAzdParameters.md, docs/DeploymentGuide.md, infra/container_app/deploy_container_app_env.bicep, infra/deploy_app_insights.bicep, infra/main.bicep, infra/main.bicepparam
=> feat: EXP environment changes for Log Analytics workspace

docs/CustomizingAzdParameters.md, docs/DeploymentGuide.md
* Updated the Deployment guide
* ...
=> feat: Added missing link to customizing azd params

docs/CustomizingAzdParameters.md, infra/container_app/deploy_container_app_env.bicep, infra/deploy_app_insights.bicep, infra/main.bicep
* Fix for Using Log analytics across subscription
* ...
=> fix: Using Log analytics across subscription

infra/abbreviations.json, infra/deploy_ai_foundry.bicep, infra/main.bicep, infra/main.json
This pull request introduces significant updates to the AI Foundry infrastructure deployment templates. The changes focus on transitioning from the "AI Hub" model to the new "AI Foundry" model, simplifying resource dependencies, and updating the Bicep and JSON templates to reflect these changes. Key highlights include the addition of `aiFoundry` and `aiFoundryProject` resources, the removal of unused parameters and resources, and updates to the deployment logic.
* Replaced `aiHub` and `aiHubProject` resources with `aiFoundry` and `aiFoundryProject` resources in `infra/deploy_ai_foundry.bicep`, including updated properties such as `allowProjectManagement` and `description`. [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L54-R43) …
=> feat: Updated to latest Azure foundry project

tests/e2e-test/tests/conftest.py, tests/e2e-test/tests/test_contentProcessing_gp_tc.py
* https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/19050/
* ...
=> test: GP Test automation - removed duplicate entries in the report and updated log entries.

docs/re-use-log-analytics.md
=> docs: Update link for re-use-log-analytics.md file

infra/scripts/docker-build.ps1, infra/scripts/docker-build.sh
=> fix: set the environment variables to update/refresh the container app

infra/main.bicep, infra/main.json
* This pull request introduces updates to the Azure infrastructure deployment files (`infra/main.bicep` and `infra/main.json`) to improve security and functionality. The key changes include the addition of `principalType: 'ServicePrincipal'` across multiple role assignments and the replacement of outdated `reference()` calls with `listOutputsWithSecureValues()` for secure resource access.
* Added `principalType: 'ServicePrincipal'` to role assignments in `infra/main.bicep` for modules such as `avmKeyVault`, `avmStorageAccount`, `avmAiServices`, and `avmAppConfig`. This ensures the correct principal type is used for service roles. [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4R450) [[2]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4b …
=> fix: add principalType as 'ServicePrincipal' for role assignments

infra/main.bicep, src/ContentProcessor/conftest.py, src/ContentProcessor/pytest.ini, src/ContentProcessor/src/helpers/azure_credential_utils.py, src/ContentProcessor/src/libs/application/application_context.py, src/ContentProcessor/src/libs/azure_helper/app_configuration.py, src/ContentProcessor/src/libs/azure_helper/azure_openai.py, src/ContentProcessor/src/libs/azure_helper/content_understanding.py, src/ContentProcessor/src/libs/azure_helper/storage_blob.py, src/ContentProcessor/src/libs/pipeline/pipeline_queue_helper.py, src/ContentProcessor/src/libs/utils/remote_module_loader.py, src/ContentProcessor/src/main.py, src/ContentProcessor/src/tests/azure_helper/test_storage_blob.py, src/ContentProcessor/src/tests/conftest.py, src/ContentProcessor/src/tests/helpers/test_azure_credential_utils.py, src/ContentProcessor/src/tests/test_main.py, src/ContentProcessorAPI/app/.env.dev, src/ContentProcessorAPI/app/libs/app_configuration/helper.py, src/ContentProcessorAPI/app/libs/storage_blob/helper.py, src/ContentProcessorAPI/app/libs/storage_queue/helper.py, src/ContentProcessorAPI/app/tests/libs/test_storage_blob.py, src/ContentProcessorAPI/conftest.py, src/ContentProcessorAPI/helpers/azure_credential_utils.py, src/ContentProcessorAPI/pytest.ini, src/ContentProcessorAPI/tests/conftest.py, src/ContentProcessorAPI/tests/helpers/test_azure_credential_utils.py
This pull request introduces significant changes to improve Azure credential handling, streamline environment configuration, and enhance test coverage. The key updates include replacing `DefaultAzureCredential` with a custom utility to dynamically select credentials based on the environment, adding new test configurations and fixtures, and modifying the infrastructure to include an `APP_ENV` variable for environment-specific behavior.
* Introduced `get_azure_credential` and `get_azure_credential_async` methods in `helpers/azure_credential_utils.py` to dynamically select `DefaultAzureCredential` for development and `ManagedIdentityCredential` for production.
* Replaced direct usage of `DefaultAzureCredential` with `get_azure_credential` across multiple files, including …
=> feat: Use ManagedIdentityCredential fir Prod Workloads and DefaultAzureCredential for dev

docs/DeploymentGuide.md, infra/main.bicep, infra/main.json
=> chore: Down merge from main to dev
